In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [3]:
#create an empty list to collect reviews
reviews = []

#create an empty list to collect Seat type
seat_type = []

#create an empty list to collect stars
stars = []

#create an empty list to collect date
date = []

#create an empty list to collect country
country = []

In [4]:
for i in range(1, 40):  
    # Looping through pages
    
    page = requests.get(f"https://www.airlinequality.com/airline-reviews/british-airways/page/{i}/?sortby=post_date%3ADesc&pagesize=100")
    page.raise_for_status()  # Check for HTTP request errors
    soup = BeautifulSoup(page.text, 'html.parser')

    # Extract reviews
    review_items = soup.find_all('div', class_='text_content')
    for item in review_items:
        reviews.append(item.text.strip() if item else "Nan")

    # Extract stars (aligned with reviews)
    star_items = soup.find_all('div', class_="rating-10")[1:]
    for item in range(len(review_items)):
        try:
            if item < len(star_items) and star_items[item].span:
                stars.append(star_items[item].span.text.strip())
            else:
                stars.append("Nan")
        except AttributeError:
            stars.append("Nan")

    # Extract seat types (aligned with reviews)
    seat_type_rows = soup.find_all('td', class_='review-rating-header cabin_flown')
    for item in range(len(review_items)):
        if item < len(seat_type_rows) and seat_type_rows[item].find_next_sibling('td'):
            seat_type.append(seat_type_rows[item].find_next_sibling('td').text.strip())
        else:
            seat_type.append("Nan")

    # Extract dates
    for item in soup.find_all('time'):
        date.append(item.text.strip() if item else "Nan")

    # Extract country information
    for item in soup.find_all('h3'):
        try:
            if item.find('span') and item.find('span').next_sibling:
                country.append(item.find('span').next_sibling.strip("()"))
            else:
                country.append("Nan")
        except:
            print(f"Error extracting country on page {i}")
            country.append("Nan")

In [5]:
#checking the count of stars

len(stars)

3896

In [6]:
#checking the count of date

len(date)

3896

In [7]:
#checking country counts

len(country)

3896

In [8]:
#checking the count of reviews

len(reviews)

3896

In [9]:
#checking count of seat Type

len(seat_type)

3896

In [10]:
#Creating a Pandas DataFrame from the list collected during scraping

df = pd.DataFrame({"reviews": reviews, "seat_type": seat_type, "date": date, "country": country, "stars": stars})

In [11]:
df

,reviews,seat_type,date,country,stars
0,✅ Trip Verified | I'm so fraustrated. My fli...,Economy Class,29th November 2024,(United Kingdom),1
1,✅ Trip Verified | We have sat on this plane fo...,Economy Class,23rd November 2024,(United Kingdom),1
2,Not Verified | British Airways stranding my w...,Economy Class,18th November 2024,(United States),1
3,✅ Trip Verified | Although like many these d...,Economy Class,17th November 2024,(United Kingdom),4
4,✅ Trip Verified | This flight was British Airw...,Business Class,15th November 2024,(United Kingdom),10
...,...,...,...,...,...
3891,Flew LHR - VIE return operated by bmi but BA a...,Economy Class,29th August 2012,(United Kingdom),10
3892,LHR to HAM. Purser addresses all club passenge...,Business Class,28th August 2012,(United Kingdom),9
3893,My son who had worked for British Airways urge...,Economy Class,12th October 2011,(United Kingdom),5
3894,London City-New York JFK via Shannon on A318 b...,Premium Economy,11th October 2011,(United States),4
3895,SIN-LHR BA12 B747-436 First Class. Old aircraf...,First Class,9th October 2011,(United Kingdom),4

In [12]:
#checking the first 20  rows in the DataFrame

df.head(20)

,reviews,seat_type,date,country,stars
0,✅ Trip Verified | I'm so fraustrated. My fli...,Economy Class,29th November 2024,(United Kingdom),1
1,✅ Trip Verified | We have sat on this plane fo...,Economy Class,23rd November 2024,(United Kingdom),1
2,Not Verified | British Airways stranding my w...,Economy Class,18th November 2024,(United States),1
3,✅ Trip Verified | Although like many these d...,Economy Class,17th November 2024,(United Kingdom),4
4,✅ Trip Verified | This flight was British Airw...,Business Class,15th November 2024,(United Kingdom),10
5,Not Verified | The worst airline I have ever f...,Economy Class,13th November 2024,(Australia),1
6,"✅ Trip Verified | Disappointing service, pla...",Economy Class,8th November 2024,(Iceland),3
7,✅ Trip Verified | A transit visa is required...,Economy Class,8th November 2024,(Singapore),1
8,✅ Trip Verified | I was surprised to receive...,Economy Class,7th November 2024,(Turkey),3
9,"✅ Trip Verified | Flight cancelled, not refu...",Economy Class,7th November 2024,(Canada),1
10,"✅ Trip Verified | I had visa issues, and hen...",Premium Economy,5th November 2024,(India),1
11,✅ Trip Verified | Singapore to Heathrow with...,Business Class,5th November 2024,(United Kingdom),6
12,✅ Trip Verified | I recently travelled from ...,Economy Class,3rd November 2024,(United Kingdom),1
13,Not Verified | I paid for seats 80 A and B on...,Premium Economy,3rd November 2024,(United States),3
14,"Not Verified | The flight wasn’t that bad, alt...",Economy Class,3rd November 2024,(United Kingdom),7
15,✅ Trip Verified | I decided to treat myself a...,Premium Economy,2nd November 2024,(United Kingdom),1
16,Not Verified | I was very impressed with thei...,Economy Class,2nd November 2024,(Canada),9
17,Not Verified | The flight scheduled at 1840 l...,Economy Class,31st October 2024,(United Kingdom),1
18,✅ Trip Verified | I have been flying BA for ...,Business Class,31st October 2024,(United States),5
19,✅ Trip Verified | On arriving at Mexico Airp...,Business Class,25th October 2024,(United Kingdom),1

#### Export Data to Csv format

In [13]:
import os

In [14]:
cwd =os.getcwd()
df.to_csv(cwd+ "/BA.csv")